version: "0.0.0"

services: 
 mongo:
  image: mongo:jammy
  container_name: fams-db
  volumes: 
    - mongodb-data:/data/db
  ports:
    - 27017:27017
  
 rabbitmq:
  image: rabbitmq:management-alpine
  container_name: fams-message-broker
  volumes:
   - rabbitmq-data:/var/lib/rabbitmq
  ports:
   - 5672:5672
   - 15672:15672
  hostname: rabbitmq
  
 redis:
  image: redis:alpine
  container_name: fams-redis
  ports:
   - 6379:6379
 
 apigateway:
  depends_on:
   - userservice
   - syllabusservice
   - redis
  image: fams:api-gateway
  build:
   context: .
   dockerfile: ./FAMS.V0.ApiGateWay/Dockerfile
  container_name: fams-api-gateway
  ports:
   - 20000:80   
  
 userservice:
  depends_on: 
   - mongo
   - rabbitmq
   - redis
  image: fams:user-service
  build: 
   context: .
   dockerfile: ./FAMS.V0.Services.UserService/Dockerfile
  container_name: fams-service-user
#  ports:
#   - 10000:80

 syllabusservice:
  depends_on: 
   - mongo
   - rabbitmq
   - redis
  image: fams:syllabus-service
  build: 
   context: .
   dockerfile: ./FAMS.V0.Services.SyllabusService/Dockerfile
  container_name: fams-service-syllabus
#  ports:
#    - 10001:80
 
 authenticationservice:
  depends_on: 
   - mongo
   - rabbitmq
   - redis
  image: fams:authentication-service
  build:
   context: .
   dockerfile: ./FAMS.V0.Services.AuthenticationService/Dockerfile
  container_name: fams-service-authentication




volumes: 
  mongodb-data:
   name: mongodb-data
  rabbitmq-data:
   name: rabbitmq-data